/**
 * 
 */
package dawang.assignment2.exception;

/**
 * @author Da Wang
 * @andrew_id dawang
 * 
 * If the file read in the program has lines with more than 5 scores, it will
 * throw this exception.
 */
public class IncorrectScoreNumberException extends Exception {
	
	/**
	 * default serailID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	public IncorrectScoreNumberException(String msg){
		super(msg);
	}

}
