/**
 * 
 */
package dawang.assignment2.exception;

/**
 * @author Da Wang
 * @andrew_id dawang
 * 
 * If the file read in the program has more than 41 lines (that is, more than
 * 40 students, it will throw this exception.
 */
public class TooManyStudentException extends Exception {
	/**
	 * default serailID generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;

	public TooManyStudentException(String msg){
		super(msg);
	}
}
